# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check https://fabricmc.net/develop/
minecraft_version=26.1.2
loader_version=0.19.2
fabric_version=0.148.0+26.1.2

# Java Properties
java_version=25

# Mod Properties
mod_version=1.0.0
maven_group=com.botpvp
archives_base_name=botpvp

# Supported Minecraft versions (also supports 26.1.1)
supported_versions=26.1.1,26.1.2
